spring:
  datasource:
    url: jdbc:h2:mem:recipesdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

# Hibernate Search (Lucene directory)
hibernate:
  search:
    backend:
      directory:
        type: local-heap

# Resilience4j defaults (can be tuned)
resilience4j:
  retry:
    instances:
      recipesClient:
        max-attempts: 3
        wait-duration: 500ms
  circuitbreaker:
    instances:
      recipesClient:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
